#!/bin/bash
cd $( dirname "$@")

echo -n "Choose a format among 7z, tar or zip: "
read format
while [ "$format" != "7z" -a "$format" != "tar" -a "$format" != "zip" ]
do
echo "Wrong format"; sleep 1
echo -n "Choose a format among 7z, tar or zip: "
read format
done
if [[ "$format" == "7z" ]]; then 		\
	7z a "$@".7z "$@"
elif [[ "$format" == "tar" ]]; then 		\
	7z a "$@".tar "$@"
elif [[ "$format" == "zip" ]]; then		\
	7z a "$@".zip "$@"
fi
	