#!/bin/bash
cd $( dirname "$@")

echo -n "Choose a format among 7z, tar, tar.gz, gz or zip: "
read format

while [ "$format" != "7z" -a "$format" != "tar" -a "$format" != "tar.gz" -a "$format" != "gz" -a "$format" != "zip" ]
do
	echo "Wrong format"; sleep 1
	echo -n "Choose a format among 7z, tar.gz, gz or zip: "
	read format
done

if [ "$format" == "tar" -o "$format" == "tar.gz" -o "$format" == "gz" ]
then
	tar -cvzf "$@"."$format" "$@"
else
	7zr a "$@"."$format" "$@"
fi

echo "Archive $@.$format successfully created"; sleep 3