#!/bin/bash
cd $( dirname "$@")

format="$@"
file="${format#*.}"

if [ "$file" != "7z" -a "$file" != "tar" -a "$file" != "tar.gz" -a "$file" != "gz" -a "$file" != "zip" ]
then
	echo "Wrong file"; sleep 1

elif [ "$file" == "7z" -o "$file" == "zip" ]
then
	7zr x "$@"
else
	tar xvf "$@"
fi