#!/bin/sh
# FFmppeg Linux screen recorder
#
#REC_iface=$(pactl list sources short | awk '{print$2}' | grep 'source')
REC_iface=$(pactl list sources short | awk '{print$2}' | grep 'monitor')
SCREEN_res=$(xrandr -q --current | grep '*' | awk '{print$1}')

ffmpeg -f pulse -i $REC_iface -ac 2 -acodec mp3 -f x11grab -r 15 -s $SCREEN_res -i :0.0 -vcodec libx264 -crf 1 -preset ultrafast "$(date)".mp4
